### ISSUE TITLE
proof passing incorrectly when using the setUp function.

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1778]
Given this Solidity contract 
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

error CoffeeBreak();

contract Counter {
    uint256 public number;

    function setNumber(uint256 newNumber, bool inLuck) public {
        number = newNumber;
        if (newNumber == 0xC0FFEE && inLuck == true) {
            revert CoffeeBreak();
        }
    }
}
```

and the test contract 
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "../src/Counter.sol";
import "../src/KEVMCheats.sol";

contract CounterTest is Test, KEVMCheats {
    Counter public counter;

   function setUp() public {
       counter = new Counter();
       counter.setNumber(0, false);
   }

    function testSetNumber(uint256 n, bool inLuck) public {
        kevm.infiniteGas();
        counter.setNumber(n, inLuck);
        assertEq(counter.number(), n);
    }
}

```

When running the command below, I can see two proofs passing for the `setUp` function and the `testSetNumber`.

```sh
kevm foundry-prove --test CounterTest.testSetNumber -v
```

```sh
INFO 2023-04-26 12:00:18,904 kevm_pyk.foundry - Running tests: ['CounterTest.testSetNumber']                                                                                                                
INFO 2023-04-26 12:00:18,904 kevm_pyk.foundry - Running setup functions in parallel: ['CounterTest.setUp']                                                                                                  
INFO 2023-04-26 12:00:18,905 kevm_pyk.foundry - Initializing KCFG for test: CounterTest.setUp                    
INFO 2023-04-26 12:05:28,403 kevm_pyk.utils - Proof passed: CounterTest.setUp
INFO 2023-04-26 12:05:28,404 kevm_pyk.foundry - Running test functions in parallel: ['CounterTest.testSetNumber']
INFO 2023-04-26 12:05:28,405 kevm_pyk.foundry - Initializing KCFG for test: CounterTest.testSetNumber
INFO 2023-04-26 12:05:28,405 kevm_pyk.foundry - Using setup method CounterTest.setUp for test: CounterTest.testSetNumber
INFO 2023-04-26 12:05:28,426 pyk.proof.reachability - Reading APRProof from file CounterTest.setUp: out/ag_proofs/8fc3eaeb4e22113f82572cdf4f102757eb20f4089036309634eae23374fbc7bc.json
INFO 2023-04-26 12:05:28,547 kevm_pyk.foundry - Expanding macros in initial state for test: CounterTest.testSetNumber
INFO 2023-04-26 12:05:28,587 kevm_pyk.foundry - Expanding macros in target state for test: CounterTest.testSetNumber
INFO 2023-04-26 12:09:15,996 kevm_pyk.utils - Proof passed: CounterTest.testSetNumber
```

The `testSetNumber` proof should fail because of the `revert` method, and the proof fails successfully when the `setUp` logic is moved inside the test.

**Comment by anvacaru** [comment]
In addition, I cannot launch the interactive debugger
```bash
anvacaru@desktop demo$ kevm foundry-view-kcfg CounterTest.testSetNumber
Traceback (most recent call last):
  File "/nix/store/gfqm2sq7wk6jnlzzya8akzi042mvzbli-python3.10-kevm-pyk-1.0.125/bin/.kevm-pyk-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/gfqm2sq7wk6jnlzzya8akzi042mvzbli-python3.10-kevm-pyk-1.0.125/lib/python3.10/site-packages/kevm_pyk/__main__.py", line 72, in main
    execute(**vars(args))
  File "/nix/store/gfqm2sq7wk6jnlzzya8akzi042mvzbli-python3.10-kevm-pyk-1.0.125/lib/python3.10/site-packages/kevm_pyk/__main__.py", line 529, in exec_foundry_view_kcfg
    ag_proof = APRProof.read_proof(test, ag_proofs_dir)
  File "/nix/store/1flvpp91y6gk4k4nklk11i49di4bbi9c-python3.10-pyk-0.1.265/lib/python3.10/site-packages/pyk/proof/reachability.py", line 45, in read_proof
    return APRProof.from_dict(proof_dict, proof_dir=proof_dir)
  File "/nix/store/1flvpp91y6gk4k4nklk11i49di4bbi9c-python3.10-pyk-0.1.265/lib/python3.10/site-packages/pyk/proof/reachability.py", line 59, in from_dict
    cfg = KCFG.from_dict(dct['cfg'])
  File "/nix/store/1flvpp91y6gk4k4nklk11i49di4bbi9c-python3.10-pyk-0.1.265/lib/python3.10/site-packages/pyk/kcfg/kcfg.py", line 316, in from_dict
    cfg.create_split(source_id, targets)
  File "/nix/store/1flvpp91y6gk4k4nklk11i49di4bbi9c-python3.10-pyk-0.1.265/lib/python3.10/site-packages/pyk/kcfg/kcfg.py", line 854, in create_split
    raise ValueError(f'Cannot create split node with less than 2 targets: {source_id} -> {splits}')
ValueError: Cannot create split node with less than 2 targets: 6e02292658d62eacb4239851729626fa3aa9e98209f98d774e210066e98db936 -> [('6e02292658d62eacb4239851729626fa3aa9e98209f98d774e210066e98db936', CSu
bst(subst=Subst(_subst=FrozenDict({})), constraints=()))]
```

**Comment by nwatson22** [comment]
@anvacaru I tried to reproduce this and the proof is failing for me on master. Is it still happening that it's passing for you?

**Comment by anvacaru** [comment]
No, it is failing as expected. Thank you!
