### ISSUE TITLE
`Directory does not exist` error in `kevm prove`

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/evm-semantics#2156]
`kevm prove` throws `Directory does not exist: /private/var/folders/ks/1p8zyp5j7xz_v1krhl4l17tm0000gn/T/tmpg3f4qrfq` error:

```
kevm provelemmas.k --definition ../out/kompiled --spec-module LEMMAS-SPEC --verbose                   
Traceback (most recent call last):
  File "/nix/store/kwf9prdhjkr6rlagnrk3bzg08lhwfqg4-python3.10-kevm-pyk-1.0.337/bin/.kevm-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/kwf9prdhjkr6rlagnrk3bzg08lhwfqg4-python3.10-kevm-pyk-1.0.337/lib/python3.10/site-packages/kevm_pyk/__main__.py", line 80, in main
    execute(**vars(args))
  File "/nix/store/kwf9prdhjkr6rlagnrk3bzg08lhwfqg4-python3.10-kevm-pyk-1.0.337/lib/python3.10/site-packages/kevm_pyk/__main__.py", line 311, in exec_prove
    kevm = KEVM(definition_dir, use_directory=save_directory, bug_report=bug_report)
  File "/nix/store/kwf9prdhjkr6rlagnrk3bzg08lhwfqg4-python3.10-kevm-pyk-1.0.337/lib/python3.10/site-packages/kevm_pyk/kevm.py", line 161, in __init__
    KProve.__init__(
  File "/nix/store/ijz3nc8j9ypxbl60x574ab10j1wrj719-python3.10-pyk-0.1.486/lib/python3.10/site-packages/pyk/ktool/kprove.py", line 172, in __init__
    super().__init__(
  File "/nix/store/ijz3nc8j9ypxbl60x574ab10j1wrj719-python3.10-pyk-0.1.486/lib/python3.10/site-packages/pyk/ktool/krun.py", line 52, in __init__
    super().__init__(
  File "/nix/store/ijz3nc8j9ypxbl60x574ab10j1wrj719-python3.10-pyk-0.1.486/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 199, in __init__
    check_dir_path(use_directory)
  File "/nix/store/ijz3nc8j9ypxbl60x574ab10j1wrj719-python3.10-pyk-0.1.486/lib/python3.10/site-packages/pyk/utils.py", line 433, in check_dir_path
    raise ValueError(f'Directory does not exist: {path}')
ValueError: Directory does not exist: /private/var/folders/ks/1p8zyp5j7xz_v1krhl4l17tm0000gn/T/tmpg3f4qrfq
```

A workaround for this issue is to create a folder beforehand and provide the path to it as an argument to `--save-directory`
```
kevm provelemmas.k --definition ../out/kompiled --spec-module LEMMAS-SPEC --save-directory ../new_dir
```

This might be a Mac-specific issue.

**Comment by nwatson22** [comment]
I was able to reproduce this on Ubuntu. I think the problem is [here](https://github.com/runtimeverification/evm-semantics/blob/caeb2df7ace2e65bd5579e172fdb2a7655c0d2aa/kevm-pyk/src/kevm_pyk/__main__.py#L309C12-L309C41) where we use `tempfile.TemporaryDirectory()`, which is intended to be used with `with`, so it immediately deletes the temp directory right after.
