### ISSUE TITLE
Failure to make libcryptopp libff libsecp256k1

### ISSUE THREAD

**Issue by ACassimiro** [runtimeverification/evm-semantics#2339]
When following the README instructions to install the `evm-semantics.plugin` on a machine with Ubuntu 22.04.3, I'm getting an error on the instruction `CXX=clang++-14 poetry -C kevm-pyk run kdist --verbose build evm-semantics.plugin`. The process fails with the final message in the logs being:

```
INFO 2024-03-07 09:48:36,529 pyk.utils - Completed in 68.248s with status 2: make libcryptopp libff libsecp256k1 -j3
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/acassimiro/.cache/pypoetry/virtualenvs/kevm-pyk-87ImhLoL-py3.10/lib/python3.10/site-packages/pyk/kdist/_kdist.py", line 157, in _build_target
    target.target.build(output_dir, deps=self._deps(target), args=args, verbose=verbose)
  File "/home/acassimiro/Documents/rv/evm-semantics/kevm-pyk/src/kevm_pyk/kdist/plugin.py", line 67, in build
    run_process(
  File "/home/acassimiro/.cache/pypoetry/virtualenvs/kevm-pyk-87ImhLoL-py3.10/lib/python3.10/site-packages/pyk/utils.py", line 427, in run_process
    res.check_returncode()
  File "/usr/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '('make', 'libcryptopp', 'libff', 'libsecp256k1', '-j3')' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/acassimiro/.cache/pypoetry/virtualenvs/kevm-pyk-87ImhLoL-py3.10/lib/python3.10/site-packages/pyk/kdist/_kdist.py", line 160, in _build_target
    raise RuntimeError(f'Build failed: {target_id.full_name}') from err
RuntimeError: Build failed: evm-semantics.plugin
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/acassimiro/.cache/pypoetry/virtualenvs/kevm-pyk-87ImhLoL-py3.10/bin/kdist", line 8, in <module>
    sys.exit(main())
  File "/home/acassimiro/.cache/pypoetry/virtualenvs/kevm-pyk-87ImhLoL-py3.10/lib/python3.10/site-packages/pyk/kdist/__main__.py", line 28, in main
    _exec_build(**vars(args))
  File "/home/acassimiro/.cache/pypoetry/virtualenvs/kevm-pyk-87ImhLoL-py3.10/lib/python3.10/site-packages/pyk/kdist/__main__.py", line 52, in _exec_build
    kdist.build(
  File "/home/acassimiro/.cache/pypoetry/virtualenvs/kevm-pyk-87ImhLoL-py3.10/lib/python3.10/site-packages/pyk/kdist/_kdist.py", line 120, in build
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: Build failed: evm-semantics.plugin
```

The full error log is available here: [output.txt](https://github.com/runtimeverification/evm-semantics/files/14524762/output.txt)

I'm currently trying to obtain more information on what is leading to this error message being triggered, but all I can gather up to this point is that something unexpected is going on while trying to build some libraries, as stated in the excerpt `Command '('make', 'libcryptopp', 'libff', 'libsecp256k1', '-j3')' returned non-zero exit status 2`.

**Comment by palinatolmach** [comment]
The error I'm seeing in the logs is
```
[  5%] Building CXX object depends/CMakeFiles/zm.dir/ate-pairing/src/zm2.cpp.o
configure.ac:20: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: error: automake failed with exit status: 1
make: *** [Makefile:78: /tmp/kdist-evm-semantics-plugin-ehn8ca7p/build/libsecp256k1/lib/pkgconfig/libsecp256k1.pc] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by palinatolmach** [comment]
One solution that I [found](https://stackoverflow.com/questions/18978252/error-libtool-library-used-but-libtool-is-undefined) suggests to install `libtool`, i.e.,
```
sudo apt-get install libtool
```
Can you please try that?

**Comment by ACassimiro** [comment]
@palinatolmach installing `libtool` solved this issue. Thanks a lot for the suggestion.

Is it the case that `libtool` might be a missing dependency in the dependency list?
